services:
  postgres:
    image: postgres:16-alpine
    container_name: saludplena_pg
    environment:
      POSTGRES_USER: saludplena
      POSTGRES_PASSWORD: saludplena
      POSTGRES_DB: saludplena_demo
    ports:
      - "5432:5432"
    volumes:
      - saludplena_pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: saludplena_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  saludplena_pg_data:
